language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcgal-dev git cmake g++ libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

  - cd ./test/
  - ./run_tests
