language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcgal-dev git cmake g++ libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev

script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - mkdir build
  - cd build
  - cmake ..
  - make

    - cd ../test/
  - ./run_tests

  - cd ../examples

  - echo "Running Unit Cube Example"
  - ../bin/mesher -i unitcube/unit_cube.inr -e unitcube/electrodes.txt  -p unitcube/input_idx.txt -o unitcubeexample -d unitcube/output/

  - echo "Running Neonate Example"
  - ../bin/mesher -i  neonatescalp/NNscalp.inr -e neonatescalp/NNscalp_elecINRpos.txt  -p neonatescalp/NNscalp_param.txt -o NNexample -d neonatescalp/output/

  - echo "Running Brain Example"
  - ../bin/mesher -i brain/input.inr -e brain/Electrodes.txt -p brain/input_idx.txt -o brainexample -d brain/output/
