language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcgal-dev git cmake g++
  - sudo mv /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1 /usr/lib/x86_64-linux-gnu/libGLU.so

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

  - cd../test/
  - ./run_tests
