function [Mesh] = loadmesh(fname)
%READMESH reads mesh from tetra and vert csv files into Mesh structure
%   Detailed explanation goes here
electrode_positions=csvread([fname '.electrodes']); 
verticies=csvread([fname '_vertices.csv']);
tetra=csvread([fname '_tetra.csv']);
[params,vals]=readparamfile([fname '.parameters']);
gndx=vals(find(strcmp(params,'groundposition.x:')));
gndy=vals(find(strcmp(params,'groundposition.y:')));
gndz=vals(find(strcmp(params,'groundposition.z:')));

gnd_pos = [gndx, gndy, gndz];

Mesh.Tetra=tetra(:,1:4);
Mesh.Nodes=verticies(:,1:3);
Mesh.mat_ref=tetra(:,5);
Mesh.elec_pos=electrode_positions;
Mesh.gnd_pos=gnd_pos;

end



function [params, vals] = readparamfile(paramname)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\djave\Tanks\Neonate\Meshing\output\low_res\NNmesh_small.parameters
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/25 15:23:14

%% Initialize variables.
delimiter = ' ';
startRow = 2;

%% Format for each line of text:
formatSpec = '%s%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(paramname,'r');

%% Read columns of data according to the format.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

params = dataArray{:, 1};
vals = dataArray{:, 2};

end
